<a href="https://colab.research.google.com/github/monirsk/Computer_Vision_Learning/blob/main/00_Introduction_to_tensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to tensors


In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#create tensors with tf.constant()

scalar = tf.constant(7 )
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
# creating a vector

vector = tf.constant([10,6])
print(vector)

tf.Tensor([10  6], shape=(2,), dtype=int32)


In [ ]:
vector.ndim

1

In [ ]:
# creating a matrix

matrix = tf.constant([[10,4],
                      [6,7]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [ 6,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#creating another matrix

another_matrix = tf.constant([[10.,7., 4.],
                              [2.,4.,5.]] , dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10.,  7.,  4.],
       [ 2.,  4.,  5.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#let's create a tensor

tensor = tf.constant ([[[1,2,3],
                        [2,3,4]],

                       [[10,20,30],
                       [30,40,50]],

                       [[11,33,44],[77,88,99]]


                       ])
tensor



<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[10, 20, 30],
        [30, 40, 50]],

       [[11, 33, 44],
        [77, 88, 99]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# The outcome of our learning:

* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimentional array of numbers
* Tensor: an n-dimentional array of numbers (n can be any number, if n=0 then the tensor is called scalar, n=1 makes it a vector, n=2 is matrix )

### Creating tensors with tf.Variable

In [ ]:
changeable_tensor = tf.Variable([10,7])

unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# we can change values of variable tensors but not the constant tensors

changeable_tensor[0].assign(120)
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([120,   7], dtype=int32)>


### Creating random tensors

Random tensor are of tensors of some random size of random numbers

In [ ]:
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))


random_2 = (tf.random.Generator.from_seed(42)).normal(shape=(3,2))
random_1,random_2, random_1 ==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of element in a tensor



In [ ]:
#(valuable for when you want to shuffle your data so the inherent order does not effect learning)

not_shuffled = tf.constant([[10,7],
                              [4,5],
                              [6,9]])

print(not_shuffled)
print(not_shuffled.ndim)

tf.Tensor(
[[10  7]
 [ 4  5]
 [ 6  9]], shape=(3, 2), dtype=int32)
2


In [ ]:
tf.random.set_seed(9)  #setting global seed
tf.random.shuffle(not_shuffled)  # randomly shuffles the tensors along with its first dimension


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [10,  7],
       [ 6,  9]], dtype=int32)>

In [ ]:
import tensorflow as tf

# Create a tensor to be shuffled
not_shuffled = tf.constant([[1, 2], [3, 4], [5, 6]])

# Shuffle the tensor with a specified seed
shuffled_tensor_1 = tf.random.shuffle(not_shuffled, seed=9)
shuffled_tensor_2 = tf.random.shuffle(not_shuffled, seed=9)



print("Shuffled Tensor 1:")
print(shuffled_tensor_1)
print("Shuffled Tensor 2:")
print(shuffled_tensor_2)

## the seed is not working

Shuffled Tensor 1:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shuffled Tensor 2:
tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)


# Other ways to make tensors

In [ ]:
#Create a tensor of all ones

tf.ones([10,4])

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Turning numpy array into tensors

import numpy as np

numpy_A = np.arange(1,25)
print(numpy_A)

A = tf.constant(numpy_A, shape=(2,3,4))
print(A)
print(A.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int64)
3


# Getting information from tensors
* Shape tensor.shape
* Rank tensor.ndim
* Axis or dimension
* Size tf.size(tensor)



In [ ]:

tensor_five = tf.zeros([2,3,4,5])
print(tensor_five)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [ ]:
print("Data type of every elemetn : ", tensor_five.dtype)
print('Number of dimensions (rank):', tensor_five.ndim)
print('Shape of tensor is : ', tensor_five.shape)

print('Total number of elements in our tensor : ', tf.size(tensor_five))
print('Total number of elements in our tensor : ', tf.size(tensor_five).numpy())

Data type of every elemetn :  <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor is :  (2, 3, 4, 5)
Total number of elements in our tensor :  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor :  120


# Tensors can be indexed just like python lists


In [3]:
# Get the first two element of each dimensions.

rank_4_tensor = tf.zeros(shape = [2,3,4,5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [4]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [5]:
# create a rank 2 tensor (2 dimension)

rank_2_tensor = tf.constant([[10,7],[3,4]])

In [6]:
rank_2_tensor.ndim, rank_2_tensor.shape, rank_2_tensor.dtype


(2, TensorShape([2, 2]), tf.int32)

In [8]:
# get the last item of each of row of our rank two tensor

rank_2_tensor [:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [9]:
#add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Manipultaing Tensors (Tensor Operatipon)

Basic operations:
+,-,*,/

these are element wise operation


In [11]:
tensor = tf.constant([[10,7],[3,4]])
tensor+10   # adding values to tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [13]:
tensor  # the original tensor remain unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [14]:
tensor = tensor +10  # now the original will be changed
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [15]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

# Matrix Multiplication

In [16]:
print(tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


In [17]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [18]:
print(tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


In [19]:
tensor*tensor # element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]], dtype=int32)>

In [21]:
t1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t2 = tf.constant([[3,5],[6,7],[1,8]])
t1,t2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [23]:
t1.shape, t1.ndim
t2.shape, t2.ndim

(TensorShape([3, 2]), 2)

In [24]:
t3 = tf.matmul(t1,t2)
t3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [25]:
# matrix multiplkication with Python operator '@'

t1@t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>